[pytest]
asyncio_mode = auto
testpaths = tests/e2e
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    e2e: marks tests as end-to-end tests (deselect with '-m "not e2e"')

[tool:pytest]
addopts = --headed --browser chromium --slowmo 1000 --video=on --screenshot=on
